# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mmlab_lmm/Programs/cRVE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mmlab_lmm/Programs/cRVE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmlab_lmm/Programs/cRVE/CMakeFiles /home/mmlab_lmm/Programs/cRVE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmlab_lmm/Programs/cRVE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crve

# Build rule for target.
crve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crve
.PHONY : crve

# fast build rule for target.
crve/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/build
.PHONY : crve/fast

src/CRVE/CRVE.o: src/CRVE/CRVE.cpp.o
.PHONY : src/CRVE/CRVE.o

# target to build an object file
src/CRVE/CRVE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/CRVE.cpp.o
.PHONY : src/CRVE/CRVE.cpp.o

src/CRVE/CRVE.i: src/CRVE/CRVE.cpp.i
.PHONY : src/CRVE/CRVE.i

# target to preprocess a source file
src/CRVE/CRVE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/CRVE.cpp.i
.PHONY : src/CRVE/CRVE.cpp.i

src/CRVE/CRVE.s: src/CRVE/CRVE.cpp.s
.PHONY : src/CRVE/CRVE.s

# target to generate assembly for a file
src/CRVE/CRVE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/CRVE.cpp.s
.PHONY : src/CRVE/CRVE.cpp.s

src/CRVE/CalcAreaAndVolume.o: src/CRVE/CalcAreaAndVolume.cpp.o
.PHONY : src/CRVE/CalcAreaAndVolume.o

# target to build an object file
src/CRVE/CalcAreaAndVolume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/CalcAreaAndVolume.cpp.o
.PHONY : src/CRVE/CalcAreaAndVolume.cpp.o

src/CRVE/CalcAreaAndVolume.i: src/CRVE/CalcAreaAndVolume.cpp.i
.PHONY : src/CRVE/CalcAreaAndVolume.i

# target to preprocess a source file
src/CRVE/CalcAreaAndVolume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/CalcAreaAndVolume.cpp.i
.PHONY : src/CRVE/CalcAreaAndVolume.cpp.i

src/CRVE/CalcAreaAndVolume.s: src/CRVE/CalcAreaAndVolume.cpp.s
.PHONY : src/CRVE/CalcAreaAndVolume.s

# target to generate assembly for a file
src/CRVE/CalcAreaAndVolume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/CalcAreaAndVolume.cpp.s
.PHONY : src/CRVE/CalcAreaAndVolume.cpp.s

src/CRVE/GetGmshFileInfo.o: src/CRVE/GetGmshFileInfo.cpp.o
.PHONY : src/CRVE/GetGmshFileInfo.o

# target to build an object file
src/CRVE/GetGmshFileInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/GetGmshFileInfo.cpp.o
.PHONY : src/CRVE/GetGmshFileInfo.cpp.o

src/CRVE/GetGmshFileInfo.i: src/CRVE/GetGmshFileInfo.cpp.i
.PHONY : src/CRVE/GetGmshFileInfo.i

# target to preprocess a source file
src/CRVE/GetGmshFileInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/GetGmshFileInfo.cpp.i
.PHONY : src/CRVE/GetGmshFileInfo.cpp.i

src/CRVE/GetGmshFileInfo.s: src/CRVE/GetGmshFileInfo.cpp.s
.PHONY : src/CRVE/GetGmshFileInfo.s

# target to generate assembly for a file
src/CRVE/GetGmshFileInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/GetGmshFileInfo.cpp.s
.PHONY : src/CRVE/GetGmshFileInfo.cpp.s

src/CRVE/JudgeFuns.o: src/CRVE/JudgeFuns.cpp.o
.PHONY : src/CRVE/JudgeFuns.o

# target to build an object file
src/CRVE/JudgeFuns.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/JudgeFuns.cpp.o
.PHONY : src/CRVE/JudgeFuns.cpp.o

src/CRVE/JudgeFuns.i: src/CRVE/JudgeFuns.cpp.i
.PHONY : src/CRVE/JudgeFuns.i

# target to preprocess a source file
src/CRVE/JudgeFuns.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/JudgeFuns.cpp.i
.PHONY : src/CRVE/JudgeFuns.cpp.i

src/CRVE/JudgeFuns.s: src/CRVE/JudgeFuns.cpp.s
.PHONY : src/CRVE/JudgeFuns.s

# target to generate assembly for a file
src/CRVE/JudgeFuns.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/JudgeFuns.cpp.s
.PHONY : src/CRVE/JudgeFuns.cpp.s

src/CRVE/LableBC.o: src/CRVE/LableBC.cpp.o
.PHONY : src/CRVE/LableBC.o

# target to build an object file
src/CRVE/LableBC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/LableBC.cpp.o
.PHONY : src/CRVE/LableBC.cpp.o

src/CRVE/LableBC.i: src/CRVE/LableBC.cpp.i
.PHONY : src/CRVE/LableBC.i

# target to preprocess a source file
src/CRVE/LableBC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/LableBC.cpp.i
.PHONY : src/CRVE/LableBC.cpp.i

src/CRVE/LableBC.s: src/CRVE/LableBC.cpp.s
.PHONY : src/CRVE/LableBC.s

# target to generate assembly for a file
src/CRVE/LableBC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/LableBC.cpp.s
.PHONY : src/CRVE/LableBC.cpp.s

src/CRVE/PrintInfo.o: src/CRVE/PrintInfo.cpp.o
.PHONY : src/CRVE/PrintInfo.o

# target to build an object file
src/CRVE/PrintInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/PrintInfo.cpp.o
.PHONY : src/CRVE/PrintInfo.cpp.o

src/CRVE/PrintInfo.i: src/CRVE/PrintInfo.cpp.i
.PHONY : src/CRVE/PrintInfo.i

# target to preprocess a source file
src/CRVE/PrintInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/PrintInfo.cpp.i
.PHONY : src/CRVE/PrintInfo.cpp.i

src/CRVE/PrintInfo.s: src/CRVE/PrintInfo.cpp.s
.PHONY : src/CRVE/PrintInfo.s

# target to generate assembly for a file
src/CRVE/PrintInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/PrintInfo.cpp.s
.PHONY : src/CRVE/PrintInfo.cpp.s

src/CRVE/ReadGmshFile.o: src/CRVE/ReadGmshFile.cpp.o
.PHONY : src/CRVE/ReadGmshFile.o

# target to build an object file
src/CRVE/ReadGmshFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadGmshFile.cpp.o
.PHONY : src/CRVE/ReadGmshFile.cpp.o

src/CRVE/ReadGmshFile.i: src/CRVE/ReadGmshFile.cpp.i
.PHONY : src/CRVE/ReadGmshFile.i

# target to preprocess a source file
src/CRVE/ReadGmshFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadGmshFile.cpp.i
.PHONY : src/CRVE/ReadGmshFile.cpp.i

src/CRVE/ReadGmshFile.s: src/CRVE/ReadGmshFile.cpp.s
.PHONY : src/CRVE/ReadGmshFile.s

# target to generate assembly for a file
src/CRVE/ReadGmshFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadGmshFile.cpp.s
.PHONY : src/CRVE/ReadGmshFile.cpp.s

src/CRVE/ReadMsh2File.o: src/CRVE/ReadMsh2File.cpp.o
.PHONY : src/CRVE/ReadMsh2File.o

# target to build an object file
src/CRVE/ReadMsh2File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadMsh2File.cpp.o
.PHONY : src/CRVE/ReadMsh2File.cpp.o

src/CRVE/ReadMsh2File.i: src/CRVE/ReadMsh2File.cpp.i
.PHONY : src/CRVE/ReadMsh2File.i

# target to preprocess a source file
src/CRVE/ReadMsh2File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadMsh2File.cpp.i
.PHONY : src/CRVE/ReadMsh2File.cpp.i

src/CRVE/ReadMsh2File.s: src/CRVE/ReadMsh2File.cpp.s
.PHONY : src/CRVE/ReadMsh2File.s

# target to generate assembly for a file
src/CRVE/ReadMsh2File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadMsh2File.cpp.s
.PHONY : src/CRVE/ReadMsh2File.cpp.s

src/CRVE/ReadMsh4File.o: src/CRVE/ReadMsh4File.cpp.o
.PHONY : src/CRVE/ReadMsh4File.o

# target to build an object file
src/CRVE/ReadMsh4File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadMsh4File.cpp.o
.PHONY : src/CRVE/ReadMsh4File.cpp.o

src/CRVE/ReadMsh4File.i: src/CRVE/ReadMsh4File.cpp.i
.PHONY : src/CRVE/ReadMsh4File.i

# target to preprocess a source file
src/CRVE/ReadMsh4File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadMsh4File.cpp.i
.PHONY : src/CRVE/ReadMsh4File.cpp.i

src/CRVE/ReadMsh4File.s: src/CRVE/ReadMsh4File.cpp.s
.PHONY : src/CRVE/ReadMsh4File.s

# target to generate assembly for a file
src/CRVE/ReadMsh4File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ReadMsh4File.cpp.s
.PHONY : src/CRVE/ReadMsh4File.cpp.s

src/CRVE/Run.o: src/CRVE/Run.cpp.o
.PHONY : src/CRVE/Run.o

# target to build an object file
src/CRVE/Run.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/Run.cpp.o
.PHONY : src/CRVE/Run.cpp.o

src/CRVE/Run.i: src/CRVE/Run.cpp.i
.PHONY : src/CRVE/Run.i

# target to preprocess a source file
src/CRVE/Run.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/Run.cpp.i
.PHONY : src/CRVE/Run.cpp.i

src/CRVE/Run.s: src/CRVE/Run.cpp.s
.PHONY : src/CRVE/Run.s

# target to generate assembly for a file
src/CRVE/Run.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/Run.cpp.s
.PHONY : src/CRVE/Run.cpp.s

src/CRVE/SaveMesh.o: src/CRVE/SaveMesh.cpp.o
.PHONY : src/CRVE/SaveMesh.o

# target to build an object file
src/CRVE/SaveMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/SaveMesh.cpp.o
.PHONY : src/CRVE/SaveMesh.cpp.o

src/CRVE/SaveMesh.i: src/CRVE/SaveMesh.cpp.i
.PHONY : src/CRVE/SaveMesh.i

# target to preprocess a source file
src/CRVE/SaveMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/SaveMesh.cpp.i
.PHONY : src/CRVE/SaveMesh.cpp.i

src/CRVE/SaveMesh.s: src/CRVE/SaveMesh.cpp.s
.PHONY : src/CRVE/SaveMesh.s

# target to generate assembly for a file
src/CRVE/SaveMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/SaveMesh.cpp.s
.PHONY : src/CRVE/SaveMesh.cpp.s

src/CRVE/ShapeFuns.o: src/CRVE/ShapeFuns.cpp.o
.PHONY : src/CRVE/ShapeFuns.o

# target to build an object file
src/CRVE/ShapeFuns.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ShapeFuns.cpp.o
.PHONY : src/CRVE/ShapeFuns.cpp.o

src/CRVE/ShapeFuns.i: src/CRVE/ShapeFuns.cpp.i
.PHONY : src/CRVE/ShapeFuns.i

# target to preprocess a source file
src/CRVE/ShapeFuns.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ShapeFuns.cpp.i
.PHONY : src/CRVE/ShapeFuns.cpp.i

src/CRVE/ShapeFuns.s: src/CRVE/ShapeFuns.cpp.s
.PHONY : src/CRVE/ShapeFuns.s

# target to generate assembly for a file
src/CRVE/ShapeFuns.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/CRVE/ShapeFuns.cpp.s
.PHONY : src/CRVE/ShapeFuns.cpp.s

src/StringUtils.o: src/StringUtils.cpp.o
.PHONY : src/StringUtils.o

# target to build an object file
src/StringUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/StringUtils.cpp.o
.PHONY : src/StringUtils.cpp.o

src/StringUtils.i: src/StringUtils.cpp.i
.PHONY : src/StringUtils.i

# target to preprocess a source file
src/StringUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/StringUtils.cpp.i
.PHONY : src/StringUtils.cpp.i

src/StringUtils.s: src/StringUtils.cpp.s
.PHONY : src/StringUtils.s

# target to generate assembly for a file
src/StringUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/StringUtils.cpp.s
.PHONY : src/StringUtils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crve.dir/build.make CMakeFiles/crve.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crve"
	@echo "... src/CRVE/CRVE.o"
	@echo "... src/CRVE/CRVE.i"
	@echo "... src/CRVE/CRVE.s"
	@echo "... src/CRVE/CalcAreaAndVolume.o"
	@echo "... src/CRVE/CalcAreaAndVolume.i"
	@echo "... src/CRVE/CalcAreaAndVolume.s"
	@echo "... src/CRVE/GetGmshFileInfo.o"
	@echo "... src/CRVE/GetGmshFileInfo.i"
	@echo "... src/CRVE/GetGmshFileInfo.s"
	@echo "... src/CRVE/JudgeFuns.o"
	@echo "... src/CRVE/JudgeFuns.i"
	@echo "... src/CRVE/JudgeFuns.s"
	@echo "... src/CRVE/LableBC.o"
	@echo "... src/CRVE/LableBC.i"
	@echo "... src/CRVE/LableBC.s"
	@echo "... src/CRVE/PrintInfo.o"
	@echo "... src/CRVE/PrintInfo.i"
	@echo "... src/CRVE/PrintInfo.s"
	@echo "... src/CRVE/ReadGmshFile.o"
	@echo "... src/CRVE/ReadGmshFile.i"
	@echo "... src/CRVE/ReadGmshFile.s"
	@echo "... src/CRVE/ReadMsh2File.o"
	@echo "... src/CRVE/ReadMsh2File.i"
	@echo "... src/CRVE/ReadMsh2File.s"
	@echo "... src/CRVE/ReadMsh4File.o"
	@echo "... src/CRVE/ReadMsh4File.i"
	@echo "... src/CRVE/ReadMsh4File.s"
	@echo "... src/CRVE/Run.o"
	@echo "... src/CRVE/Run.i"
	@echo "... src/CRVE/Run.s"
	@echo "... src/CRVE/SaveMesh.o"
	@echo "... src/CRVE/SaveMesh.i"
	@echo "... src/CRVE/SaveMesh.s"
	@echo "... src/CRVE/ShapeFuns.o"
	@echo "... src/CRVE/ShapeFuns.i"
	@echo "... src/CRVE/ShapeFuns.s"
	@echo "... src/StringUtils.o"
	@echo "... src/StringUtils.i"
	@echo "... src/StringUtils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

